### ISSUE TITLE
update? :)

### ISSUE THREAD

**Issue by jerabaul29** [ETLCPP/etl-arduino#2]
Would it be possible to get an updated version of this? :) Seems like a few bug fixes etc have been pushed to https://github.com/ETLCPP/etl/commits/master since last update here :) .

**Comment by jwellbelove** [comment]
I have a small update to push in the main line code, and then I'll update the Arduino repository.

**Comment by jerabaul29** [comment]
Amazing, many thanks :) .

**Comment by jerabaul29** [comment]
Many thanks for the update :) .
